[build]
  command = "npm run build"  # Adjust if you have a custom build process
  publish = "dist"  # Make sure this is where your built static files reside

[functions]
  directory = "netlify/functions"  # The location of your Netlify functions
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true